# بيانات المنتجات الأولية — بترتحّل لقاعدة البيانات تلقائياً أول تشغيل فقط
# بعد كده أي إضافة/تعديل/حذف تتم من لوحة التحكم مباشرة، مش من هنا

PRODUCTS_SEED = {
    "batman-arkham-knight-xb": {
        "name": "Batman Arkham Knight Xbox", "nameEn": "Batman Arkham Knight Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 270, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/gLBtLMZ6/d550f93b3de7b68015516483344066ec.jpg",
        "description": "Batman: Arkham Knight هي لعبة أكشن وعالم مفتوح تضعك في دور باتمان لحماية مدينة جوثام من أخطر أعدائه.",
        "descriptionEn": "Batman: Arkham Knight is an action and open-world game protecting Gotham City.",
    },
    "FC-26-xb": {
        "name": "FC 26 Xbox", "nameEn": "FC 26 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 500, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/xThLH0G/IMG-20260703-030147.jpg",
        "description": "EA SPORTS FC 26 هي أحدث ألعاب كرة القدم من EA بتجربة واقعية وأوضاع متنوعة.",
        "descriptionEn": "EA SPORTS FC 26 is the latest football game from EA.",
    },
    "red-dead-redempiton-2-ps": {
        "name": "Red Dead Redempiton 2 Playstation", "nameEn": "Rad Dead Redempiton 2 Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 550, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/DgsCfdSS/download.jpg",
        "description": "Red Dead Redemption 2 لعبة أكشن ومغامرات في الغرب الأمريكي عام 1899.",
        "descriptionEn": "Red Dead Redemption 2 is set in the American West in 1899.",
    },
    "Watch-dogs-leigon-ps": {
        "name": "Watch dogs leigon Playstation", "nameEn": "Watch dogs leigon Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 450, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/V0vSS1pY/download-1.jpg",
        "description": "Watch Dogs: Legion لعبة عالم مفتوح في لندن المستقبلية.",
        "descriptionEn": "Watch Dogs: Legion is set in a futuristic London.",
    },
    "Assassins-creed-mirage-xb": {
        "name": "Assassins Creed Mirage Xbox", "nameEn": "Assassins Creed Mirage Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 650, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/PZP2ngRh/images-6.jpg",
        "description": "Assassin's Creed Mirage تعود بجذور السلسلة إلى التخفي والاغتيالات في بغداد.",
        "descriptionEn": "Assassin's Creed Mirage is set in ninth-century Baghdad.",
    },
    "Assassins-creed-shadow-xb": {
        "name": "Assassins Creed Shadow Xbox", "nameEn": "Assassins Creed Shadow Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 800, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/R4t7JHZJ/images-5.jpg",
        "description": "Assassin's Creed Shadows في اليابان الإقطاعية بشخصيتين مختلفتين.",
        "descriptionEn": "Assassin's Creed Shadows is set in feudal Japan.",
    },
    "red-dead-redempiton-2-xb": {
        "name": "Red Dead Redempiton 2 Xbox", "nameEn": "Rad Dead Redempiton 2 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 800, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/DgsCfdSS/download.jpg",
        "description": "Red Dead Redemption 2 لعبة أكشن ومغامرات في الغرب الأمريكي عام 1899.",
        "descriptionEn": "Red Dead Redemption 2 is set in the American West in 1899.",
    },
    "far-cry-6-ps": {
        "name": "Far Cry 6 Playstation", "nameEn": "Far Cry 6 Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 550, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/dsshPYGt/images-7.jpg",
        "description": "Far Cry 6 لعبة أكشن وعالم مفتوح في جزيرة يارا الخيالية.",
        "descriptionEn": "Far Cry 6 is set on the fictional island of Yara.",
    },
    "Resident-Evil-Village-ps": {
        "name": "Resident Evil Village Playstation", "nameEn": "Resident Evil Village Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 550, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/7JSK063C/download-2.jpg",
        "description": "Resident Evil Village لعبة رعب وبقاء من منظور الشخص الأول.",
        "descriptionEn": "Resident Evil Village is a first-person horror and survival game.",
    },
    "Spider-Man-ps": {
        "name": "Spider maximum Playstation", "nameEn": "Spider Man Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 550, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/XxbJzdJ6/images-8.jpg",
        "description": "Marvel's Spider-Man لعبة أكشن وعالم مفتوح بشخصية بيتر باركر.",
        "descriptionEn": "Marvel's Spider-Man where you play as Peter Parker.",
    },
    "Spider-Man-Miles-Morales-ps": {
        "name": "Spider Man Miles Morales PlayStation", "nameEn": "Spider Man Miles Morales Playstation",
        "platformTag": "PS5", "category": "playstation-games",
        "note": "بريمري", "noteEn": "Primary", "price": 650, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/jZQMRZ1d/download-3.jpg",
        "description": "Marvel's Spider-Man: Miles Morales تتابع قصة مايلز موراليس.",
        "descriptionEn": "Marvel's Spider-Man: Miles Morales follows the story of Miles Morales.",
    },
    "Forza-Horizon-5-xb": {
        "name": "Forza Horizon 5 Xbox", "nameEn": "Forza Horizon 5 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 850, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/8g3XLhPF/images-9.jpg",
        "description": "Forza Horizon 5 لعبة سباقات بعالم مفتوح تأخذك إلى المكسيك.",
        "descriptionEn": "Forza Horizon 5 takes you to Mexico.",
    },
    "Gift-Card-10-USD-xb": {
        "name": "Gift Card 10 USD Xbox", "nameEn": "Gift Card 10 USD Xbox",
        "platformTag": "XBOX", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 600, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/kVwMrxvB/IMG-20260702-151848.png",
        "description": "بطاقة هدايا 10 دولار امريكي لمنصة Xbox، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 10 USD For Xbox. Delivery within 2 hours after order confirmation.",
    },
    "Gift-Card-50-USD-xb": {
        "name": "Gift Card 50 USD Xbox", "nameEn": "Gift Card 50 USD Xbox",
        "platformTag": "XBOX", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 2600, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/Z660Vz0d/2-20260702-152657.png",
        "description": "بطاقة هدايا 50 دولار امريكي لمنصة Xbox، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 50 USD For Xbox. Delivery within 2 hours after order confirmation.",
    },
    "Gift-Card-100-USD-xb": {
        "name": "Gift Card 100 USD Xbox", "nameEn": "Gift Card 100 USD Xbox",
        "platformTag": "XBOX", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 5250, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/0R9Rxf5k/2-20260702-153014.png",
        "description": "بطاقة هدايا 100 دولار امريكي لمنصة Xbox، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 100 USD For Xbox. Delivery within 2 hours after order confirmation.",
    },
    "Gift-Card-10-USD-ps": {
        "name": "Gift Card 10 USD Playstation", "nameEn": "Gift Card 10 USD Playstation",
        "platformTag": "PlayStation", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 610, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/XffCKqB7/IMG-20260702-153249.png",
        "description": "بطاقة هدايا 10 دولار امريكي لمنصة playstation، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 10 USD For playstation. Delivery within 2 hours after order confirmation.",
    },
    "Gift-Card-50-USD-ps": {
        "name": "Gift Card 50 USD Playstation", "nameEn": "Gift Card 50 USD PlayStation",
        "platformTag": "playstation", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 2700, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/kt02gjm/2-20260702-162226.png",
        "description": "بطاقة هدايا 50 دولار امريكي لمنصة playstation، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 50 USD For playstation. Delivery within 2 hours after order confirmation.",
    },
    "Gift-Card-100-USD-ps": {
        "name": "Gift Card 100 USD PlayStation", "nameEn": "Gift Card 100 USD PlayStation",
        "platformTag": "PlayStation", "category": "gift-cards",
        "note": " بطاقة هدايا ", "noteEn": "Gift Card", "price": 5600, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/Fksq8grS/ey-Jp-ZCI6-Im1f-Nm-E2-NTJl-YWNj-MTk4-ODE5-MWE1-Mz-Ey-Yz-Jk-Zjlk-ODVi-Ym-M6c2-Vka-W1lbn-Q6-Ly9k-ZWZj-ZGNi-Yz.jpg",
        "description": "بطاقة هدايا 100 دولار امريكي لمنصة playstation، تسليم خلال ساعتين بحد اقصى بعد تأكيد الطلب.",
        "descriptionEn": "Gift Card 100 USD For playstation. Delivery within 2 hours after order confirmation.",
    },
    "Stray-Xbox": {
        "name": "Stray Xbox", "nameEn": "Stray Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 450, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/wZtxWCsW/images-10.jpg",
        "description": "Stray لعبة مغامرات فريدة تضعك في دور قط ضائع داخل مدينة مستقبلية.",
        "descriptionEn": "Stray puts you in the role of a lost cat in a futuristic city.",
    },
    "Call-of-duty-black-ops-6-xb": {
        "name": "Call of duty black ops 6 Xbox", "nameEn": "Call of duty black ops 6 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 780, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/PZv1hM6G/MV5-BYj-E3-OGFk-Mm-It-ZGMz-OC00-Ym-Vj-LWE5-Zm-Yt-Nzcx-MTk0-OTY5-NTU2-Xk-Ey-Xk-Fqc-Gc.jpg",
        "description": "Call of Duty: Black Ops 6 لعبة تصويب من منظور الشخص الأول بحملة سينمائية مشوقة.",
        "descriptionEn": "Call of Duty: Black Ops 6 is a first-person shooter with an exciting campaign.",
    },
    "The-crew-2-xb": {
        "name": "The crew 2 Xbox", "nameEn": "The crew 2 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 350, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/dw7Lv2s1/1-IVy-Dh-CRLet-Fhmg-Osg-F84-Eafuh-GV6-Sw-TPjmnp2-Y7-H9x4jju-REk-B8-P1dism-Mvp-DYk.jpg",
        "description": "The Crew 2 لعبة سباقات بعالم مفتوح داخل الولايات المتحدة.",
        "descriptionEn": "The Crew 2 is an open-world racing game set in the United States.",
    },
    "A-Plague-Tale-Innocence-xb": {
        "name": "A Plague Tale Innocence Xbox", "nameEn": "A Plague Tale Innocence Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 380, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://assets.mycast.io/posters/a-plague-tale-innocence-fan-casting-poster-380962-medium.jpg?1694389502",
        "description": "A Plague Tale Innocence لعبة مغامرات وقصة تدور في فرنسا خلال العصور الوسطى.",
        "descriptionEn": "A Plague Tale Innocence is set in France during the Middle Ages.",
    },
    "A-Plague-Tale-Requiem-xb": {
        "name": "A Plague Tale Requiem Xbox", "nameEn": "A Plague Tale Requiem Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 700, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/fLTk9tN/mixcollage-11-dec-2024-03-58-pm-1132.jpg",
        "description": "A Plague Tale Requiem تواصل رحلة أميسيا وشقيقها هوجو في عالم يعج بالأوبئة والمخاطر.",
        "descriptionEn": "A Plague Tale Requiem continues the journey of Amicia and her brother Hugo.",
    },
    "Mortal-Kombat-11-xb": {
        "name": "Mortal Kombat 11 Xbox", "nameEn": "Mortal Kombat 11 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 400, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/MDdXPG1s/OIP.webp",
        "description": "Mortal Kombat 11 لعبة قتال تقدم مواجهات عنيفة وسريعة بين أشهر شخصيات السلسلة.",
        "descriptionEn": "Mortal Kombat 11 is a fighting game featuring fast and violent battles.",
    },
    "Dying-light-2-xb": {
        "name": "Dying light 2 Xbox", "nameEn": "Dying light 2 Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 600, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/n8CsFvp1/3b8a68cf-f202-46ff-9b5e-7b795a4073e8.webp",
        "description": "Dying Light 2 لعبة أكشن ورعب بعالم مفتوح تدور أحداثها بعد انتشار وباء عالمي.",
        "descriptionEn": "Dying Light 2 is set after a global pandemic.",
    },
    "Need-For-Speed-heat-deluxe-edition-xb": {
        "name": "Need For Speed heat deluxe edition Xbox", "nameEn": "Need For Speed heat deluxe edition Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 150, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/6J4g5xGf/OIP.webp",
        "description": "Need for Speed Heat لعبة سباقات عالم مفتوح تجمع بين سباقات النهار وسباقات الشوارع الليلية.",
        "descriptionEn": "Need for Speed Heat combines official daytime races with street racing.",
    },
    "Need-For-Speed-Unbound-xb": {
        "name": "Need For Speed Unbound Xbox", "nameEn": "Need For Speed Unbound Xbox",
        "platformTag": "XBOX", "category": "xbox-games",
        "note": "حساب كامل", "noteEn": "Full account", "price": 700, "inStock": True,
        "currency": {"ar": "ج.م", "en": "EGP"},
        "image": "https://i.ibb.co/C58b1fpk/need-for-speed-unbound-fan-casting-poster-406056-medium.jpg",
        "description": "Need for Speed Unbound لعبة سباقات عالم مفتوح تتميز بأسلوب فني مبتكر.",
        "descriptionEn": "Need for Speed Unbound features an innovative art style.",
    },
}
